services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: rocket-gw:latest
    container_name: rocket-gateway
    restart: unless-stopped
    ports:
      - "4760:80"
    networks:
      rocket-alpha-net:
        aliases:
          - rocket-gateway

networks:
  rocket-alpha-net:
    external: true
